# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codeseeds
email: info@codeseeds.io
description: > # this means to ignore newlines until "baseurl:"
 Codeseeds is a site to learn about tips and techniques for data analysis, Ruby on Rails, JavaScript, and front end code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codeseeds.io" # the base hostname & protocol for your site
twitter_username: CodeSeeds
github_username:  codeseedsproject
codepen_username:

links:
 - title: home
   url: /
 - title: articles
   url: /articles
 - title: projects
   url: /projects
 - title: about
   url: /about



# Build settings
markdown: kramdown
